// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFOy92aoP0Y-grw8W0T1gl5AqAcwWJMk',
    appId: '1:175549252348:web:f0627e59618ce5e4850d79',
    messagingSenderId: '175549252348',
    projectId: 'news-aggregator-app-ac9e1',
    authDomain: 'news-aggregator-app-ac9e1.firebaseapp.com',
    storageBucket: 'news-aggregator-app-ac9e1.firebasestorage.app',
    measurementId: 'G-52D7J1D45G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGl7qBSWJdNbjbMpLaneDVOOAEuuvs2_w',
    appId: '1:175549252348:android:e63a5aa30f09bbd1850d79',
    messagingSenderId: '175549252348',
    projectId: 'news-aggregator-app-ac9e1',
    storageBucket: 'news-aggregator-app-ac9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiF7JxkwAooXpXtI8Sx5AZzQlrBhEWnkk',
    appId: '1:175549252348:ios:5ea6b4d873f9c65b850d79',
    messagingSenderId: '175549252348',
    projectId: 'news-aggregator-app-ac9e1',
    storageBucket: 'news-aggregator-app-ac9e1.firebasestorage.app',
    iosBundleId: 'com.example.newsAggregatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiF7JxkwAooXpXtI8Sx5AZzQlrBhEWnkk',
    appId: '1:175549252348:ios:5ea6b4d873f9c65b850d79',
    messagingSenderId: '175549252348',
    projectId: 'news-aggregator-app-ac9e1',
    storageBucket: 'news-aggregator-app-ac9e1.firebasestorage.app',
    iosBundleId: 'com.example.newsAggregatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFOy92aoP0Y-grw8W0T1gl5AqAcwWJMk',
    appId: '1:175549252348:web:ea14f38a2e9e2a46850d79',
    messagingSenderId: '175549252348',
    projectId: 'news-aggregator-app-ac9e1',
    authDomain: 'news-aggregator-app-ac9e1.firebaseapp.com',
    storageBucket: 'news-aggregator-app-ac9e1.firebasestorage.app',
    measurementId: 'G-WW0P54BDLZ',
  );
}
